version: '3.1'

services:

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql
    secrets:
      - db_password
    networks:
      - app-network

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      user: $UID:$GID
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', 'https://${WORDPRESS_SITE_DOMAIN}');
        define('WP_HOME', 'https://${WORDPRESS_SITE_DOMAIN}');
        define('FORCE_SSL_ADMIN', true);
    volumes:
      - ./wp-content:/var/www/html/wp-content
    secrets:
      - db_password
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WORDPRESS_SITE_DOMAIN=${WORDPRESS_SITE_DOMAIN}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/private:/etc/ssl/private

secrets:
  db_password:
    file: secrets/db_password.txt

volumes:
  wp-content:
  mysql:

networks:
  app-network:
    driver: bridge